name: LoveAdaptation
version: 1.0.0
main: me.lovelace.LoveAdaptation.LoveAdaptation
api-version: '26.2'
author: Lovelace
description: Dynamic environment adaptation plugin for Minecraft.
softdepend: [PlaceholderAPI, DeluxeMenus, LoveCore, LoveClans, LoveBehavior]

commands:
  loveadaptation:
    description: Main command for LoveAdaptation plugin
    aliases: [ la, adaptation, adaptations, адаптация ]
    permission: loveadaptation.use
  loveadaptationadmin:
    description: Admin command for LoveAdaptation plugin
    aliases: [ laadmin, лаадмин ]
    usage: /loveadaptationadmin <reload|reset|check|givepotion>
    permission: loveadaptation.admin

permissions:
  loveadaptation.use:
    description: Allows opening adaptation menu and checking info
    default: true
  loveadaptation.admin:
    description: Allows using admin commands like reset, check, reload
    default: op